<?php


namespace KemperAdmin\Helper\View;


use App\Helper\View\AbstractViewHelper;

class HierarchyList extends AbstractViewHelper
{
    public function render($element)
    {
        $this->inlineScript()->prependFile($this->basePath("js/form/elements/hierarchylist.js"));

        $hierarchyList =  parent::render($element); // TODO: Change the autogenerated stub
        $hidden = $element->isHidden() ? " hidden " : "";
        $html = <<<HTML
<div class="hierarchyList" {$hidden}>
<button type="button" class="btn btn-default btn-sm close-hierarchyList" aria-label="Left Align">
<i class="fas fa-arrow-left"></i>
</button>
<br>
{$hierarchyList}
</div>
HTML;


        return $html;
    }


}