<?php
/**
 * Date: 2/24/2020
 * Time: 8:09 PM
 */

namespace App\Di;
use Zend\ServiceManager\ServiceManager as ZendServiceManager;

class ServiceManager extends ZendServiceManager
{
    public function configure(array $config)
    {
        return parent::configure($config); // TODO: Change the autogenerated stub
    }

    public function get($name)
    {
        return parent::get($name); // TODO: Change the autogenerated stub
    }

    public function build($name, array $options = null)
    {
        return parent::build($name, $options); // TODO: Change the autogenerated stub
    }

}