<?php
/**
 * @var ViewModel $helper
 */
/**
 * @var PhpRenderer $this
 * @var float $net
 * @var float $newSales
 * @var string $refunds
 * @var AbstractTemplate $hierarchy
 * @var string $filterdropdowndashboard
 * @var string $hierarchyListTemplate
 *
 */

$this->headTitle("Kemper Health - Production");
$this->inlineScript()->appendFile($this->basePath("js/kemperadmin/hierarchy-sidenav.js"));


use App\Template\AbstractTemplate;
use Zend\View\Helper\ViewModel;
use Zend\View\Renderer\PhpRenderer; ?>
<div id="right-side-nav" class="slide-out-right side-nav sn-bg-4" style="margin-top: 67px !important">
    <ul class="custom-scrollbar-right">
        <li>
            <?=$hierarchy->getHtml();?>

        </li>
    </ul>
    <div class="sidenav-bg mask-strong"></div>
</div>
<a data-activates="right-side-nav" class="hierarchy-collapse float-right nav-link waves-effect">
    <span class="clearfix d-none d-sm-inline-block">Hierarchy</span>
    <i class="fas fa-sitemap"></i>
</a>
<section class="mt-md-4 pt-md-2 mb-5">
    <!-- First row -->
    <div class="row allCards">

        <!-- First column -->
        <div class="col-xl-3 col-md-6 mb-xl-0 mb-4">

            <!-- Card -->
            <div class="card card-cascade cascading-admin-card sales-card-whole">

                <!-- Card Data -->
                <div class="admin-up salesCard">
                    <i class="far fa-money-bill-alt primary-color mr-3 z-depth-2"></i>
                    <div class="data salesData" id="sales-data-state">
                        <p class="text-uppercase">Total Sales</p>
                        <h4 class="font-weight-bold salesNumber">$<?= number_format($newSales) ?></h4>
                    </div>
                </div>

                <!-- Card content -->
                <div class="card-body card-body-cascade">
                    <div class="progress mb-3">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 25%" aria-valuenow="25"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <p class="card-text">Better than last week (25%)</p>
                </div>

            </div>
            <!-- Card -->

        </div>
        <!-- First column -->

        <!-- Second column -->
        <div class="col-xl-3 col-md-6 mb-xl-0 mb-4">

            <!-- Card -->
            <div class="card card-cascade cascading-admin-card">

                <!-- Card Data -->
                <div class="admin-up refundCard">
                    <i class="far fa-money-bill-alt warning-color mr-3 z-depth-2"></i>
                    <div class="data refundData" id="refund-data-card">
                        <p class="text-uppercase">Total Refunds</p>
                        <h4 class="font-weight-bold refundNumber">$<?= number_format($refunds) ?></h4>
                    </div>
                </div>

                <!-- Card content -->
                <div class="card-body card-body-cascade">
                    <div class="progress mb-3">
                        <div class="progress-bar red accent-2" role="progressbar" style="width: 25%" aria-valuenow="25"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <p class="card-text">Worse than last week (25%)</p>
                </div>

            </div>
            <!-- Card -->

        </div>
        <!-- Second column -->

        <!-- Third column -->
        <div class="col-xl-3 col-md-6 mb-md-0 mb-4">

            <!-- Card -->
            <div class="card card-cascade cascading-admin-card">

                <!-- Card Data -->
                <div class="admin-up netCard">
                    <i class="fas fa-chart-pie light-blue lighten-1 mr-3 z-depth-2"></i>
                    <div class="data netData" id="net-data-card">
                        <p class="text-uppercase">Total Net</p>
                        <h4 class="font-weight-bold netNumber">$<?= number_format($net) ?></h4>
                    </div>
                </div>

                <!-- Card content -->
                <div class="card-body card-body-cascade">
                    <div class="progress mb-3">
                        <div class="progress-bar red accent-2" role="progressbar"
                             style="width:  <?= $disposedOpenPercent ?>%" aria-valuenow="75"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <p class="card-text">Worse than last week (75%)</p>
                </div>

            </div>
            <!-- Card -->

        </div>
        <!-- Third column -->

    </div>
    <!-- First row -->

</section>
<!-- Section: Analytical panel -->

<section class="mb-5">

    <!-- Card -->
    <div class="card card-cascade narrower">

        <!-- Section: Chart -->
        <section>

            <!-- Grid row -->
            <div class="row">

                <!-- Grid column -->
                <div class="col-xl-6 col-lg-12 mr-0 pb-2">

                    <!-- Card image -->
                    <div class="view view-cascade gradient-card-header light-blue lighten-1">
                        <h2 class="h2-responsive mb-0 font-weight-500">Production Filter</h2>
                    </div>

                    <!-- Card content -->
                    <div class="card-body card-body-cascade pb-0">

                        <!-- Panel data -->
                        <div class="row py-3 pl-4">

                            <!-- First column -->
                            <div class="col-md-6">

                                <!-- Date select -->
<!--                                --><?php //echo $this->render($chartdatafilterdropdown);?>
                                <!-- Date pickers -->
                                <div class="md-form">
                                    <input placeholder="Selected date" type="text" id="from" class="form-control datepicker">
                                    <label for="date-picker-example">From</label>
                                </div>
                                <div class="md-form">
                                    <input placeholder="Selected date" type="text" id="to" class="form-control datepicker">
                                    <label for="date-picker-example">To</label>
                                </div>
                            </div>
                            <!-- First column -->

                            <!-- Second column -->
                            <div class="col-md-6 text-right pl-xl-2 my-md-0 my-3">

                                <!-- Summary -->
                                <p>Total Disposed: <strong></strong>
                                    <button type="button" class="btn btn-info btn-sm p-2" data-toggle="tooltip" data-placement="top"
                                            title="Total bills that have been disposed"><i class="fas fa-question"></i></button>
                                </p>
                                <p>Total Un-disposed: <strong></strong>
                                    <button type="button" class="btn btn-info btn-sm p-2 mr-0" data-toggle="tooltip"
                                            data-placement="top" title="Total bills that have not been disposed"><i
                                                class="fas fa-question"></i></button>
                                </p>

                                <!-- Change chart -->
                                <!--                                <span class="min-chart my-4" id="chart-sales" data-percent="76"><span
                                                                        class="percent"></span></span>
                                                                <h5>-->
                                <span class="badge red accent-2 p-2">Change <i class="fas fa-arrow-circle-up ml-1"></i></span>
                                <button type="button" class="btn btn-info btn-sm p-2" data-toggle="tooltip" data-placement="top"
                                        title="Percentage change compared to the same period in the past"><i
                                            class="fas fa-question"></i>
                                </button>
                                </h5>

                            </div>
                            <!-- Second column -->

                        </div>
                        <!-- Panel data -->

                    </div>
                    <!-- Card content -->

                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <input type="hidden" name="disposerDataUrl" value="<?=$disposerDataUrl?>">
<!--                <input type="hidden" name="dispositionDataUrl" value="<?/*=$dispositionDataUrl*/?>">
                <input type="hidden" name="productStatsDataUrl" value="<?/*=$productStatsDataUrl*/?>">-->
                <div class="col-xl-6 col-lg-12 mb-4 pb-2">
                    <!-- Chart -->
                    <div class="view view-cascade gradient-card-header blue-gradient chart-area-sales">
                        <canvas id="kemperDashboardSales" height="175"></canvas>
                    </div>

                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->

        </section>
        <!-- Section: Chart -->


    </div>
    <!-- Card -->

</section>
<section class="mb-5">

    <!-- Card -->
    <div class="card card-cascade narrower">

        <!-- Section: Chart -->
        <section>

            <!-- Grid row -->
            <div class="row">

                <!-- Grid column -->
                <!-- Grid column -->
                <div class="col-xl-6 col-lg-12 mb-4 pb-2">

                    <!-- Chart -->
                    <div class="view view-cascade gradient-card-header blue-gradient chart-area-refunds">
                        <canvas id="kemperDashboardRefunds" height="175"></canvas>
                    </div>

                </div>

                <!-- Grid column -->
                <div class="col-xl-6 col-lg-12 mb-4 pb-2">
                    <!-- Chart -->
                    <div class="view view-cascade gradient-card-header blue-gradient chart-area-net">
                        <canvas id="kemperDashboardNet" height="175"></canvas>
                    </div>

                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->

        </section>
        <!-- Section: Chart -->


    </div>
    <!-- Card -->

</section>


<?php
$this->inlineScript()->appendFile($this->basePath("js/kemperadmin/production-dashboard.js"));
$this->inlineScript()->appendFile($this->basePath("js/filters/daterange.js"));
?>



