<?php
/**
 * @var ViewModel $helper
 */
/**
 * @var array $disposerArray
 * @var string $disposerDataUrl
 * @var string $dispositionDataUrl
 * @var string $yearlyDataUrl
 *
 */

foreach ($disposerArray as $data => $information):
    ?>
    <a class="dropdown-item chartDisposerItem" href="#"
       data-url="<?=$information['disposerDataUrl']?>"
       data-chart-disposer="<?= $information['disposer_id'] ?>"><?= $information['disposer_description'] ?></a>
<?php
endforeach;

use Zend\View\Helper\ViewModel; ?>
<script src="../../js/kemperadmin/filter-dropdown-item.js"></script>
<script src="../../js/kemperadmin/conservation-dashboard.js"></script>

<input type="hidden" name="disposerDataUrl" value="<?=$disposerDataUrl?>">
<input type="hidden" name="dispositionDataUrl" value="<?=$dispositionDataUrl?>">
<input type="hidden" name="yearlyDataUrl" value="<?=$yearlyDataUrl?>">