
<?php
/**
 * @var ViewModel $helper
 * @var Zend\View\Renderer\PhpRenderer $this
 */
/**
 * @var float $conservedPremium
 * @var float $conservedPaidPremium
 * @var string $disposedOpen
 * @var string $disposedOpenPercent
 * @var string $disposedClosed
 * @var string $disposedClosedPercent
 * @var string $totalDisposed
 * @var string $totalUnDisposed
 * @var string $chartdatafilterdropdown
 * @var string $filterdropdowndashboard
 * @var string $firstName
 * @var string $lastName
 *
 */

use Zend\View\Helper\ViewModel;

$this->headTitle("Conservation Admin - Dashboard");


$this->inlineScript()->appendFile("../../js/vendor/chart.js/Chart.min.js");
$this->inlineScript()->appendFile("../../js/vendor/demo/chart-area-demo.js");

//To display
/**
 * <?=$firstName.' '.$lastName?>
 *
 * <?php echo $this->render($filterdropdowndashboard);?>
 *
 * <?=number_format($conservedPremium)?>
 *
 * <?=number_format($conservedPaidPremium)?>
 *
 * <?=$disposedOpen?>
 *
 * <?=$disposedClosed?>
 *
 * <?=$totalDisposed?>
 *
 * <?=$totalUnDisposed?>
 *
 * List of Disposers
 * <?php echo $this->render($chartdatafilterdropdown);?>
 *
 */


?>
<!-- Section: Analytical panel -->
<section class="mt-md-4 pt-md-2 mb-5">

    <!-- First row -->
    <div class="row">

        <!-- First column -->
        <div class="col-xl-3 col-md-6 mb-xl-0 mb-4">

            <!-- Card -->
            <div class="card card-cascade cascading-admin-card">

                <!-- Card Data -->
                <div class="admin-up">
                    <i class="far fa-money-bill-alt primary-color mr-3 z-depth-2"></i>
                    <div class="data">
                        <p class="text-uppercase">Conserved Premium</p>
                        <h4 class="font-weight-bold ">$<?=number_format($conservedPremium)?></h4>
                    </div>
                </div>

                <!-- Card content -->
                <div class="card-body card-body-cascade">
                    <div class="progress mb-3">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 25%" aria-valuenow="25"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <p class="card-text">Better than last week (25%)</p>
                </div>

            </div>
            <!-- Card -->

        </div>
        <!-- First column -->

        <!-- Second column -->
        <div class="col-xl-3 col-md-6 mb-xl-0 mb-4">

            <!-- Card -->
            <div class="card card-cascade cascading-admin-card">

                <!-- Card Data -->
                <div class="admin-up">
                    <i class="far fa-money-bill-alt warning-color mr-3 z-depth-2"></i>
                    <div class="data">
                        <p class="text-uppercase">Conserved Paid</p>
                        <h4 class="font-weight-bold ">$<?=number_format($conservedPaidPremium)?></h4>
                    </div>
                </div>

                <!-- Card content -->
                <div class="card-body card-body-cascade">
                    <div class="progress mb-3">
                        <div class="progress-bar red accent-2" role="progressbar" style="width: 25%" aria-valuenow="25"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <p class="card-text">Worse than last week (25%)</p>
                </div>

            </div>
            <!-- Card -->

        </div>
        <!-- Second column -->

        <!-- Third column -->
        <div class="col-xl-3 col-md-6 mb-md-0 mb-4">

            <!-- Card -->
            <div class="card card-cascade cascading-admin-card">

                <!-- Card Data -->
                <div class="admin-up">
                    <i class="fas fa-chart-pie light-blue lighten-1 mr-3 z-depth-2"></i>
                    <div class="data">
                        <p class="text-uppercase">Disposed Open</p>
                        <h4 class="font-weight-bold "><?=$disposedOpen?></h4>
                    </div>
                </div>

                <!-- Card content -->
                <div class="card-body card-body-cascade">
                    <div class="progress mb-3">
                        <div class="progress-bar red accent-2" role="progressbar" style="width:  <?=$disposedOpenPercent?>%" aria-valuenow="75"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <p class="card-text">Worse than last week (75%)</p>
                </div>

            </div>
            <!-- Card -->

        </div>
        <!-- Third column -->

        <!-- Fourth column -->
        <div class="col-xl-3 col-md-6 mb-0">

            <!-- Card -->
            <div class="card card-cascade cascading-admin-card">

                <!-- Card Data -->
                <div class="admin-up">
                    <i class="fas fa-chart-bar red accent-2 mr-3 z-depth-2"></i>
                    <div class="data">
                        <p class="text-uppercase">Disposed Closed</p>
                        <h4 class="font-weight-bold "><?=$disposedClosed?></h4>
                    </div>
                </div>

                <!-- Card content -->
                <div class="card-body card-body-cascade">
                    <div class="progress mb-3">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: <?=$disposedClosedPercent?>%" aria-valuenow="25"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <p class="card-text">Better than last week (25%)</p>
                </div>

            </div>
            <!-- Card -->

        </div>
        <!-- Fourth column -->

    </div>
    <!-- First row -->

</section>
<!-- Section: Analytical panel -->
<section class="mb-5">

    <!-- Card -->
    <div class="card card-cascade narrower">

        <!-- Section: Chart -->
        <section>

            <!-- Grid row -->
            <div class="row">

                <!-- Grid column -->
                <div class="col-xl-6 col-lg-12 mr-0 pb-2">

                    <!-- Card image -->
                    <div class="view view-cascade gradient-card-header light-blue lighten-1">
                        <h2 class="h2-responsive mb-0 font-weight-500">Filter</h2>
                    </div>

                    <!-- Card content -->
                    <div class="card-body card-body-cascade pb-0">

                        <!-- Panel data -->
                        <div class="row py-3 pl-4">

                            <!-- First column -->
                            <div class="col-md-6">

                                <!-- Date select -->
                                <?php echo $this->render($chartdatafilterdropdown);?>
                                <!-- Date pickers -->
                                <div class="md-form">
                                    <input placeholder="Selected date" type="text" id="from" class="form-control datepicker">
                                    <label for="date-picker-example">From</label>
                                </div>
                                <div class="md-form">
                                    <input placeholder="Selected date" type="text" id="to" class="form-control datepicker">
                                    <label for="date-picker-example">To</label>
                                </div>

                            </div>
                            <!-- First column -->

                            <!-- Second column -->
                            <div class="col-md-6 text-right pl-xl-2 my-md-0 my-3">

                                <!-- Summary -->
                                <p>Total Disposed: <strong><?=$totalDisposed?></strong>
                                    <button type="button" class="btn btn-info btn-sm p-2" data-toggle="tooltip" data-placement="top"
                                            title="Total bills that have been disposed"><i class="fas fa-question"></i></button>
                                </p>
                                <p>Total Un-disposed: <strong><?=$totalUnDisposed?></strong>
                                    <button type="button" class="btn btn-info btn-sm p-2 mr-0" data-toggle="tooltip"
                                            data-placement="top" title="Total bills that have not been disposed"><i
                                            class="fas fa-question"></i></button>
                                </p>

                                <!-- Change chart -->
<!--                                <span class="min-chart my-4" id="chart-sales" data-percent="76"><span
                                        class="percent"></span></span>
                                <h5>-->
                                    <span class="badge red accent-2 p-2">Change <i class="fas fa-arrow-circle-up ml-1"></i></span>
                                    <button type="button" class="btn btn-info btn-sm p-2" data-toggle="tooltip" data-placement="top"
                                            title="Percentage change compared to the same period in the past"><i
                                            class="fas fa-question"></i>
                                    </button>
                                </h5>

                            </div>
                            <!-- Second column -->

                        </div>
                        <!-- Panel data -->

                    </div>
                    <!-- Card content -->

                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-xl-6 col-lg-12 mb-4 pb-2">
                    <!-- Chart -->
                    <div class="view view-cascade gradient-card-header blue-gradient chart-area">
                        <canvas id="earningVsDisposition" height="175"></canvas>
                    </div>

                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->

        </section>
        <!-- Section: Chart -->


    </div>
    <!-- Card -->

</section>
<section class="mb-5">

    <!-- Card -->
    <div class="card card-cascade narrower">

        <!-- Section: Chart -->
        <section>

            <!-- Grid row -->
            <div class="row">

                <!-- Grid column -->
                <!-- Grid column -->
                <div class="col-xl-6 col-lg-12 mb-4 pb-2">

                    <!-- Chart -->
                    <div class="view view-cascade gradient-card-header blue-gradient">
                        <canvas id="lineChart" height="175"></canvas>
                    </div>

                </div>

                <!-- Grid column -->
                <div class="col-xl-6 col-lg-12 mb-4 pb-2">

                    <!-- Chart -->
                    <div class="view view-cascade gradient-card-header blue-gradient">

                        <canvas id="popularDisposition" height="175"></canvas>

                    </div>

                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->

        </section>
        <!-- Section: Chart -->


    </div>
    <!-- Card -->

</section>

<!-- Section: Analytical panel -->
<!-- Initializations -->
<!--<script>
    // SideNav Initialization
    $(".button-collapse").sideNav();

    var container = document.querySelector('.custom-scrollbar');
    var ps = new PerfectScrollbar(container, {
        wheelSpeed: 2,
        wheelPropagation: true,
        minScrollbarLength: 20
    });

    // Data Picker Initialization
    $('.datepicker').pickadate();

    // Material Select Initialization
    $(document).ready(function () {
        $('.mdb-select').material_select();
    });

    // Tooltips Initialization
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })

</script>
-->
<!-- Charts -->
<script>
    // Small chart

</script>