<?php
/**
 * @var ViewModel $helper
 * @var PhpRenderer $this
 */

use Zend\View\Helper\ViewModel;
use Zend\View\Renderer\PhpRenderer;

/**
 * @var array $reportConfigs
 * @var string $classification
 */

$pageTitle = ucfirst($classification) . ' Reports';
$this->headTitle($pageTitle);

?>
<h2 class="font-weight-bold mt-lg-5 mb-5 pb-4"><strong><?= $pageTitle ?></strong></h2>
<div class="reportslist">
    <ul>
    <?php

    foreach ($reportConfigs as $reportConfig) {
        $reportCard = (new \Zend\View\Model\ViewModel([
            'reportConfig' => $reportConfig
        ]))->setTemplate('kemper-admin/report/title-card');
        echo $this->render($reportCard);
    }
    ?>
    </ul>
</div>