<?php
/**
 * @var PhpRenderer $this
 * @var ViewModel $helper
 */

/**
 * @var string $firstName
 * @var string $lastName
 * @var \App\Auth\Identity $identity
 */

use KemperAdmin\Helper\MenuConstantsInterface as MCI;
use Zend\View\Model\ViewModel;
use Zend\View\Renderer\PhpRenderer;

$identity = $this->getEngine()->identity();
if (!$identity) {
    //temp Fix - remove later
    $identity = new \App\Auth\Identity();
}
?>
<?= $this->doctype();?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/kemperIcon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath("css/mdb.min.css"))
        ->prependStylesheet($this->basePath("css/bootstrap.min.css"))
        ->prependStylesheet($this->basePath("css/custom-kemper.css"))
        ->prependStylesheet($this->basePath("css/font/all.css"))
        ->prependStylesheet($this->basePath("css/addons-pro/multi-range.min.css"))
        ->prependStylesheet($this->basePath("css/addons-pro/cards-extended.css"))
        ->prependStylesheet($this->basePath("css/addons/datatables.css"))
        ->prependStylesheet($this->basePath("css/addons/datatables-select.css"));
    ?>

    <!-- Scripts -->

    <?php
    $this->inlineScript()->prependFile($this->basePath("js/addons-pro/cards-extended.min.js"));
    $this->inlineScript()->prependFile($this->basePath("js/addons-pro/multi-range.min.js"));
    $this->inlineScript()->prependFile($this->basePath("js/addons/datatables-select.js"));
    $this->inlineScript()->prependFile($this->basePath("js/addons/datatables.js"));
    $this->inlineScript()->prependFile($this->basePath("js/vendor/jquery-easing/jquery.easing.min.js"));
    $this->inlineScript()->prependFile($this->basePath("js/vendor/bootstrap/js/bootstrap.bundle.min.js"));
    $this->inlineScript()->prependFile($this->basePath("js/mdb.min.js"));
    $this->inlineScript()->prependFile($this->basePath("js/bootstrap.min.js"));
    $this->inlineScript()->prependFile($this->basePath("js/popper.min.js"));
    $this->inlineScript()->prependFile($this->basePath("js/jquery-3.4.1.min.js"));
    ?>
</head>
<body class="fixed-sn white-skin">
<!-- Main Navigation -->
<header class="layoutnavigation">
    <!-- 1st Sidebar navigation -->
    <div id="slide-out" class="side-nav sn-bg-4 fixed" style="width: 240px; transform: translateX(-1000px);">
        <ul class="custom-scrollbar">
            <!-- Logo -->
            <li class="logo-sn waves-effect py-3 KemperImageLi">
                <div class="text-center KemperImage">
                    <a href="<?=$this->url('kemperadmin:home')?>" class="pl-0"><img src="<?=$this->basePath("img/KemperHealth_Logo_Horz_Color_Web_FINAL-4.png")?>"></a>
                </div>
            </li>
            <!-- Search Form -->
            <li>
                <form class="search-form" role="search">
                    <div class="md-form mt-0 waves-light">
                        <input type="text" class="form-control py-2" placeholder="Search">
                    </div>
                </form>
            </li>
            <!-- Side navigation links -->
            <li>
                <ul class="collapsible collapsible-accordion">

                    <li>
                        <a class="collapsible-header waves-effect arrow-r">
                            <i class="w-fa fas fa-tachometer-alt"></i>Conservation<i class="fas fa-angle-down rotate-icon"></i>
                        </a>
                        <div class="collapsible-body">
                            <ul>
                                <?php if($identity->getPriv(MCI::CONSERVATION_DASHBOARD_VIEW)):?>
                                <li>
                                    <a href="<?=$this->url('kemperadmin:conservation')?>" class="waves-effect">Dashboard</a>
                                </li>
                                <?php
                                    endif;
                                ?>
                                <?php if($identity->getPriv(MCI::CONSERVATION_REPORTS)):?>
                                <li>
                                    <a href="<?=$this->url('kemperadmin:report-center', ['classification' => 'conservation'])?>" class="waves-effect">Reports</a>
                                </li>
                                <?php
                                    endif;
                                ?>
                            </ul>
                        </div>
                    </li>
                    <?php if($identity->getPriv(MCI::PRODUCTION_DASHBOARD_VIEW)):?>

                    <li>
                        <a class="collapsible-header waves-effect arrow-r">
                            <i class="w-fa fas fa-tachometer-alt"></i>Production<i class="fas fa-angle-down rotate-icon"></i>
                        </a>
                        <div class="collapsible-body">
                            <ul>
                                <?php if($identity->getPriv(MCI::PRODUCTION_DASHBOARD_VIEW)):?>
                                <li>
                                    <a href="<?=$this->url('kemperadmin:production')?>" class="waves-effect">Dashboard</a>
                                </li>
                                <?php
                                    endif;
                                ?>
                                <?php if($identity->getPriv(MCI::PRODUCTION_REPORTS)):?>
                                <li>
                                    <a href="<?=$this->url('kemperadmin:report-center', ['classification' => 'production'])?>" class="waves-effect">Reports</a>
                                </li>
                                <?php
                                    endif;
                                ?>
                            </ul>
                        </div>
                    </li>
                    <?php
                    endif;
                    ?>
                    <!-- Simple link -->
                    <li>
                        <a href="../alerts/alerts.html" class="collapsible-header waves-effect"><i
                                    class="w-fa far fa-bell"></i>Alerts</a>
                    </li>
                    <li>
                        <a href="../modals/modals.html" class="collapsible-header waves-effect"><i
                                    class="w-fa fas fa-bolt"></i>Modals</a>
                    </li>


                </ul>
            </li>
            <!-- Side navigation links -->

        </ul>
        <div class="sidenav-bg mask-strong"></div>
    </div>
<!--    2nd sidebar navigation-->

    <nav class="navbar fixed-top navbar-toggleable-md navbar-expand-lg scrolling-navbar double-nav">

        <!-- SideNav slide-out button -->
        <div class="float-left">
            <a href="#" data-activates="slide-out" class="button-collapse"><i class="fas fa-bars"></i></a>
        </div>
        <!-- Breadcrumb -->
        <div class="breadcrumb-dn mr-auto">
            <p></p>
        </div>

        <div class="d-flex change-mode">

            <div class="ml-auto mb-0 mr-3 change-mode-wrapper">
                <button class="btn btn-outline-black btn-sm" id="dark-mode">Change Mode</button>
            </div>

            <!-- Navbar links -->
            <ul class="nav navbar-nav nav-flex-icons ml-auto">

                <!-- Dropdown -->
<!--                <li class="nav-item dropdown notifications-nav">
                    <a class="nav-link dropdown-toggle waves-effect" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <span class="badge red">3</span> <i class="fas fa-bell"></i>
                        <span class="d-none d-md-inline-block">Notifications</span>
                    </a>
                    <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">
                            <i class="far fa-money-bill-alt mr-2" aria-hidden="true"></i>
                            <span>New order received</span>
                            <span class="float-right"><i class="far fa-clock" aria-hidden="true"></i> 13 min</span>
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="far fa-money-bill-alt mr-2" aria-hidden="true"></i>
                            <span>New order received</span>
                            <span class="float-right"><i class="far fa-clock" aria-hidden="true"></i> 33 min</span>
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-chart-line mr-2" aria-hidden="true"></i>
                            <span>Your campaign is about to end</span>
                            <span class="float-right"><i class="far fa-clock" aria-hidden="true"></i> 53 min</span>
                        </a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect"><i class="fas fa-envelope"></i> <span
                                class="clearfix d-none d-sm-inline-block">Contact</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect"><i class="far fa-comments"></i> <span
                                class="clearfix d-none d-sm-inline-block">Support</span></a>
                </li>-->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect" href="#" id="userDropdown" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user"></i> <span class="clearfix d-none d-sm-inline-block">Profile</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="<?=$this->url('kemperadmin:login:logout')?>">Log Out</a>
                        <a class="dropdown-item" href="<?=$this->url('kemperadmin:users')?>">
                            <?php echo $identity->getFirstname();?></a>
                    </div>
                </li>
            </ul>
            <!-- Navbar links -->

        </div>

    </nav>
    <!-- Navbar -->


</header>
<!-- Main Navigation -->
<!-- Main layout -->
<main>
    <div class="container-fluid">
    <?= $this->content;?>
    </div>

</main>
<!-- Main layout -->

<!-- Footer -->
<footer class="page-footer font-small blue">
    <!-- Copyright -->
    <div class="footer-copyright py-3 text-center">
        <div class="container-fluid">
            © 2020 Copyright: <a href="https://kemper.com/" target="_blank">Kemper.com</a>
        </div>
    </div>
</footer>
<?= $this->inlineScript() ?>

<!-- Initializations -->
<script>
    // SideNav Initialization
    $(".button-collapse").sideNav();

    var container = document.querySelector('.custom-scrollbar');
    var ps = new PerfectScrollbar(container, {
        wheelSpeed: 2,
        wheelPropagation: true,
        minScrollbarLength: 20
    });
    $(document).ready(function () {
        $('#usersList').DataTable();
        $('#usersList_wrapper').find('label').each(function () {
            $(this).parent().append($(this).children());
        });
        $('#usersList_wrapper .dataTables_filter').find('input').each(function () {
            const $this = $(this);
            $this.attr("placeholder", "Search");
            $this.removeClass('form-control-sm');
        });
        $('#usersList_wrapper .dataTables_length').addClass('d-flex flex-row');
        $('#usersList_wrapper .dataTables_filter').addClass('md-form');
        $('#usersList_wrapper select').removeClass(
            'custom-select custom-select-sm form-control form-control-sm');
        $('#usersList_wrapper select').addClass('mdb-select');
        $('#usersList_wrapper .mdb-select').materialSelect();
        $('#usersList_wrapper .dataTables_filter').find('label').remove();
    });
</script>
</body>
</html>
