<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet("../../css/mdb.min.css")
            ->prependStylesheet("../../css/bootstrap.min.css")
        ->prependStylesheet("../../css/font/all.css");
    ?>

    <!-- Scripts -->
    <?php

    $this->inlineScript()->prependFile("../../js/vendor/jquery-easing/jquery.easing.min.js");
    $this->inlineScript()->prependFile("../../js/vendor/bootstrap/js/bootstrap.bundle.min.js");
    $this->inlineScript()->prependFile("../../js/mdb.min.js");
    $this->inlineScript()->prependFile("../../js/bootstrap.min.js");
    $this->inlineScript()->prependFile("../../js/popper.min.js");
    $this->inlineScript()->prependFile("../../js/jquery-3.4.1.min.js");

    ?>
</head>
<body class="fixed-sn white-skin">
<!-- Main Navigation -->
<header>

    <!-- Sidebar navigation -->
    <div id="slide-out" class="side-nav sn-bg-4 fixed" style="width: 240px; transform: translateX(-1000px);">
        <ul class="custom-scrollbar">

            <!-- Logo -->
            <li class="logo-sn waves-effect py-3 KemperImageLi">
                <div class="text-center KemperImage">
                    <a href="#" class="pl-0"><img src="../../img/KemperHealth_Logo_Horz_Color_Web_FINAL-4.png"></a>
                </div>
            </li>

            <!-- Search Form -->
            <li>
                <form class="search-form" role="search">
                    <div class="md-form mt-0 waves-light">
                        <input type="text" class="form-control py-2" placeholder="Search">
                    </div>
                </form>
            </li>

            <!-- Side navigation links -->
            <li>
                <ul class="collapsible collapsible-accordion">

                    <li>
                        <a class="collapsible-header waves-effect arrow-r">
                            <i class="w-fa fas fa-tachometer-alt"></i>Dashboards<i class="fas fa-angle-down rotate-icon"></i>
                        </a>
                        <div class="collapsible-body">
                            <ul>
                                <li>
                                    <a href="../dashboards/v-1.html" class="waves-effect">Version 1</a>
                                </li>
                                <li>
                                    <a href="../dashboards/v-2.html" class="waves-effect">Version 2</a>
                                </li>
                                <li>
                                    <a href="../dashboards/v-3.html" class="waves-effect">Version 3</a>
                                </li>
                                <li>
                                    <a href="../dashboards/v-4.html" class="waves-effect">Version 4</a>
                                </li>
                                <li>
                                    <a href="../dashboards/v-5.html" class="waves-effect">Version 5</a>
                                </li>
                                <li>
                                    <a href="../dashboards/v-6.html" class="waves-effect">Version 6</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <a class="collapsible-header waves-effect arrow-r">
                            <i class="w-fa fas fa-image"></i>Pages<i class="fas fa-angle-down rotate-icon"></i>
                        </a>
                        <div class="collapsible-body">
                            <ul>
                                <li>
                                    <a href="../pages/login.html" class="waves-effect">Login</a>
                                </li>
                                <li>
                                    <a href="../pages/register.html" class="waves-effect">Register</a>
                                </li>
                                <li>
                                    <a href="../pages/pricing.html" class="waves-effect">Pricing</a>
                                </li>
                                <li>
                                    <a href="../pages/about.html" class="waves-effect">About us</a>
                                </li>
                                <li>
                                    <a href="../pages/single.html" class="waves-effect">Single post</a>
                                </li>
                                <li>
                                    <a href="../pages/post.html" class="waves-effect">Post listing</a>
                                </li>
                                <li>
                                    <a href="../pages/landing.html" class="waves-effect">Landing page</a>
                                </li>
                                <li>
                                    <a href="../pages/customers.html" class="waves-effect">Customers</a>
                                </li>
                                <li>
                                    <a href="../pages/invoice.html" class="waves-effect">Invoice</a>
                                </li>
                                <li>
                                    <a href="../pages/page-creator.html" class="waves-effect">Page Creator</a>
                                </li>
                                <li>
                                    <a href="../pages/support.html" class="waves-effect">Support</a>
                                </li>
                                <li>
                                    <a href="../pages/chat.html" class="waves-effect">Chat</a>
                                </li>
                            </ul>
                        </div>
                    </li>


                    <!-- Simple link -->
                    <li>
                        <a href="../alerts/alerts.html" class="collapsible-header waves-effect"><i
                                    class="w-fa far fa-bell"></i>Alerts</a>
                    </li>
                    <li>
                        <a href="../modals/modals.html" class="collapsible-header waves-effect"><i
                                    class="w-fa fas fa-bolt"></i>Modals</a>
                    </li>


                </ul>
            </li>
            <!-- Side navigation links -->

        </ul>
        <div class="sidenav-bg mask-strong"></div>
    </div>
    <!-- Sidebar navigation -->

    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg scrolling-navbar double-nav">

        <!-- SideNav slide-out button -->
        <div class="float-left">
            <a href="#" data-activates="slide-out" class="button-collapse"><i class="fas fa-bars"></i></a>
        </div>

        <!-- Breadcrumb -->
        <div class="breadcrumb-dn mr-auto">
            <p></p>
        </div>

        <div class="d-flex change-mode">

            <div class="ml-auto mb-0 mr-3 change-mode-wrapper">
                <button class="btn btn-outline-black btn-sm" id="dark-mode">Change Mode</button>
            </div>

            <!-- Navbar links -->
            <ul class="nav navbar-nav nav-flex-icons ml-auto">

                <!-- Dropdown -->
                <li class="nav-item dropdown notifications-nav">
                    <a class="nav-link dropdown-toggle waves-effect" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <span class="badge red">3</span> <i class="fas fa-bell"></i>
                        <span class="d-none d-md-inline-block">Notifications</span>
                    </a>
                    <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">
                            <i class="far fa-money-bill-alt mr-2" aria-hidden="true"></i>
                            <span>New order received</span>
                            <span class="float-right"><i class="far fa-clock" aria-hidden="true"></i> 13 min</span>
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="far fa-money-bill-alt mr-2" aria-hidden="true"></i>
                            <span>New order received</span>
                            <span class="float-right"><i class="far fa-clock" aria-hidden="true"></i> 33 min</span>
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-chart-line mr-2" aria-hidden="true"></i>
                            <span>Your campaign is about to end</span>
                            <span class="float-right"><i class="far fa-clock" aria-hidden="true"></i> 53 min</span>
                        </a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect"><i class="fas fa-envelope"></i> <span
                                class="clearfix d-none d-sm-inline-block">Contact</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect"><i class="far fa-comments"></i> <span
                                class="clearfix d-none d-sm-inline-block">Support</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect" href="#" id="userDropdown" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user"></i> <span class="clearfix d-none d-sm-inline-block">Profile</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="login/logout">Log Out</a>
                        <a class="dropdown-item" href="#">My account</a>
                    </div>
                </li>

            </ul>
            <!-- Navbar links -->

        </div>

    </nav>
    <!-- Navbar -->

</header>
<!-- Main Navigation -->


<!-- Main layout -->
<main>

    <div class="container-fluid">
    <?= $this->content ?>

    </div>

</main>
<!-- Main layout -->

<!-- Footer -->
<footer class="page-footer pt-0 mt-5 rgba-stylish-light">

    <!-- Copyright -->
    <div class="footer-copyright py-3 text-center">
        <div class="container-fluid">
            © 2020 Copyright: <a href="https://kemper.com/" target="_blank"> Kemper.com</a>
        </div>
    </div>

</footer>
<?= $this->inlineScript() ?>

<!-- Initializations -->
<script>
    // SideNav Initialization
    $(".button-collapse").sideNav();

    var container = document.querySelector('.custom-scrollbar');
    var ps = new PerfectScrollbar(container, {
        wheelSpeed: 2,
        wheelPropagation: true,
        minScrollbarLength: 20
    });

    $(function () {
        $('#dark-mode').on('click', function (e) {

            e.preventDefault();

            $('footer, .card').toggleClass('dark-card-admin');
            $('body, .navbar').toggleClass('white-skin navy-blue-skin');
            $(this).toggleClass('white text-dark btn-outline-black');
            $('body').toggleClass('dark-bg-admin');
            $('h6, .card, p, td, th, i, li a, h4, input, label').not(
                '#slide-out i, #slide-out a, .dropdown-item i, .dropdown-item').toggleClass('text-white');
            $('.btn-dash').toggleClass('grey blue').toggleClass('lighten-3 darken-3');
            $('.gradient-card-header').toggleClass('white black lighten-4');
            $('.list-panel a').toggleClass('navy-blue-bg-a text-white').toggleClass('list-group-border');

        });
    });

</script>
</body>
</html>
