<?php
use Zend\View\Helper\ViewModel;
use Zend\View\Renderer\PhpRenderer;

/**
 * @var ViewModel $helper
 * @var PhpRenderer $this
 */
/**
 * @var array $disposerArray
 * @var string $disposerDataUrl
 * @var string $dispositionDataUrl
 * @var string $productStatsDataUrl
 *
 */
?>

<div class="d-flex">
    <div class="dropdown mr-1">
        <button type="button" class="btn badge info-color p-2 dropdown-toggle" id="dropdownMenuOffset" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false" data-offset="10,20">
            Disposers
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
       <?php foreach ($disposerArray as $data => $information):
    ?>
            <a class="dropdown-item chartDisposerItem" href="#"
               data-url="<?=$information['disposerDataUrl']?>"
               data-chart-disposer="<?= $information['disposer_id'] ?>"><?= $information['disposer_description'] ?></a>
            <?php
endforeach;
       ?>
        </div>
    </div>
</div>




<input type="hidden" name="disposerDataUrl" value="<?=$disposerDataUrl?>">
<input type="hidden" name="dispositionDataUrl" value="<?=$dispositionDataUrl?>">
<input type="hidden" name="productStatsDataUrl" value="<?=$productStatsDataUrl?>">