<div class="container mt-5">
    <!--Grid row-->
    <div class="row">
        <!--Grid column-->
        <div class="col-md-4 mb-4">
            <div class="md-form">
                <!--The "from" Date Picker -->
                <input placeholder="Selected starting date" type="text" id="startingDate" class="form-control minimal_datepicker datepicker">
                <label for="startingDate"class="active">start</label>
            </div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">
            <div class="md-form">
                <!--The "to" Date Picker -->
                <input placeholder="Selected ending date" type="text" id="endingDate" class="form-control minimal_datepicker datepicker">
                <label for="endingDate"class="active">end</label>
            </div>
        </div>
        <!--Grid column-->
    </div>
    <!--Grid row-->
</div>
<div class="btn-group">
    <div class="btn-group">
        <button type="button" class="btn btn-primary btn-lg btn-block filterSubmitKemperDashboard">Filter</button>
    </div>
</div>