<?php
/**
 * @var ViewModel $helper
 * @var PhpRenderer $this
 */

use App\Model\Entity\User;
use Zend\View\Helper\ViewModel;
use Zend\View\Renderer\PhpRenderer;

/**
 * @var User[] $users
 */
?>
      <h1 class="title h1 my-4">List Of All Users</h1>
<table  id="usersList" class="table table-striped" cellspacing="0" width="100%">
    <thead>
<tr>
    <th class="th-sm">
        Username
    </th>
    <th class="th-sm">
        Firstname
    </th>
    <th class="th-sm">
        Lastname
    </th>
    <th class="th-sm">
        Password
    </th>
    <th class="th-sm">
        Edit User
    </th>
</tr>
</thead>
            <tbody>

        <?php
        foreach ($users as $user):
        ?>

            <tr>
                <td>
                    <?=$user->getUsername()?>
                </td>
                <td>
                    <?=$user->getFirstname()?>
                </td>
                <td>
                    <?=$user->getLastname()?>
                </td>
                <td>
                    <?=$user->getPassword()?>
                </td>
                <td>
                    <a href="<?=$this->url('kemperadmin:users:edituser', ['username' => $user->getUsername()])?>">
                        <i class="far fa-edit"></i>   Edit User
                    </a>
                </td>
            </tr>
        <?php
        endforeach;
        ?>

            </tbody>
        </table>
