<?php
/**
 * @var ViewModel $helper
 * @var $privilege_production_dashboard_view
 * @var $privilege_conservation_dashboard_view
 */
use Zend\View\Model\ViewModel;

$this->headTitle("Kemper Health - Home");
?>


<div class="jumbotron">
    <h1>Welcome to <span class="font-weight-bold mt-lg-5 mb-5 pb-4">Kemper Health</span></h1>
    <p>
       Please click on one of the dashboards:
    </p>
</div>

<div class="row">


    <?php
    if($privilege_production_dashboard_view == 1):?>
        <div class="col-lg-4 col-md-12 mb-4">

            <!-- Card -->
            <div class="card card-cascade narrower">

                <!-- Card image -->
                <div class="view view-cascade gradient-card-header blue-gradient">

                    <h2 class="card-header-title">Production</h2>

                </div>
                <!-- Card image -->

                <!-- Card content -->
                <div class="card-body card-body-cascade text-center">

                    <p class="card-text">
                        Production Dashboard Content
                        This would lead you to the production dashboard to
                        see production per agent,agent or per manager</p>
                    <a href="production" class="btn btn-primary waves-effect waves-light">Proceed</a>
                </div>
                <!-- Card content -->

            </div>
            <!-- Card -->

        </div>
    <!--    <div class="card card-cascade narrower">

         Card image
        <div class="view view-cascade gradient-card-header purple-gradient">

            <h2 class="card-header-title">Mattonit</h2>

            <p>The Boar</p>

            <div class="text-center">
                Conservation Dashboard Content
                This would lead you to the conservation dashboard or
                depending on your access will lead you to
                customer service.
            </div>
        </div>
    </div>
--><!--        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">Conservation Dashboard</h2>
                </div>
                <div class="card-body">
                    <p>
                        Conservation Dashboard Content
                        This would lead you to the conservation dashboard or
                        depending on your access will lead you to
                        customer service.
                    </p>
                    <p><a class="btn btn-primary pull-right" href="conservation">Conservation</a></p>
                </div>
            </div>
    </div>
-->
    <?php
    endif;
    ?>
    <?php
    if($privilege_conservation_dashboard_view == 1):?>
        <div class="col-lg-4 col-md-12 mb-4">

            <!-- Card -->
            <div class="card card-cascade narrower">

                <!-- Card image -->
                <div class="view view-cascade gradient-card-header blue-gradient">

                    <h2 class="card-header-title">Conservation</h2>

                </div>
                <!-- Card image -->

                <!-- Card content -->
                <div class="card-body card-body-cascade text-center">

                    <p class="card-text">
                        Conservation Dashboard Content
                        This would lead you to the conservation dashboard or
                        depending on your access will lead you to
                        customer service..</p>
                    <a href="conservation" class="btn btn-primary waves-effect waves-light">Proceed</a>
                </div>
                <!-- Card content -->

            </div>
            <!-- Card -->

        </div>
        <!--        <div class="card card-cascade narrower">

                     Card image
                    <div class="view view-cascade gradient-card-header purple-gradient">

                        <h2 class="card-header-title">Mattonit</h2>

                        <p>The Boar</p>

                        <div class="text-center">
                            Conservation Dashboard Content
                            This would lead you to the conservation dashboard or
                            depending on your access will lead you to
                            customer service.
                        </div>
                    </div>
                </div>
        -->        <!--    <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title">Conservation Dashboard</h2>
                    </div>
                    <div class="card-body">
                        <p>
                            Conservation Dashboard Content
                            This would lead you to the customer service or
                            depending on your access
                        </p>
                        <p><a class="btn btn-primary pull-right" href="conservation">Conservation</a></p>
                    </div>
                </div>
            </div>-->
    <?php
    endif;
    ?>
 <!--   <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Discover Modules</h2>
            </div>
            <div class="card-body">
                <p>
                    The community is working on developing a community site to
                    serve as a repository and gallery for ZF modules. The
                    project is available <a href="https://github.com/zendframework/modules.zendframework.com">on GitHub</a>.
                    The site is currently live and currently contains a list of
                    some of the modules already available for ZF.
                </p>

                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank">Explore ZF Modules &raquo;</a></p>
            </div>
        </div>
    </div>
-->
</div>
